### ISSUE TITLE
Document how to run this via pytest

### ISSUE THREAD

**Issue by jdahlin** [dropbox/pyannotate#11]
It would be great to know how to invoke this via normal pytest, which I believe would be one of the primary use cases. pytest does not provide a simple main().

Alternatively a pytest plugin would probably be even nicer, so you could just run:

```
pip install pytest-annotate
pytest --annnotate-types
```

**Comment by gvanrossum** [comment]
I'm not very familiar with pytest fixtures, so don't expect me to write that plugin; but I think you could write a fixture that calls init_types_collection() and a decorator that calls resume()/pause() around a test, and then in the cleanup phase of the fixture call dump_stats().

Anyway, there are many different scenarios. Have you tried any of them manually yet?

**Comment by gsalgado** [comment]
I was able to run this via pytest with the following conftest.py

```
import pytest
from pyannotate_runtime import collect_types

collect_types.init_types_collection()


@pytest.fixture(autouse=True)
def collect_types_fixture():
    collect_types.resume()
    yield
    collect_types.pause()


def pytest_sessionfinish(session, exitstatus):
    collect_types.dump_stats("type_info.json")
```

**Comment by gvanrossum** [comment]
Thanks, I've now added this to the 'example' directory in the project.
