### ISSUE TITLE
Type annotation does not with in Python 3.5

### ISSUE THREAD

**Issue by jabdoa2** [dropbox/pyannotate#15]
For some reason pyannotate with the workaround from #12 does not annotate my files:

```
PYTHONPATH=/usr/local/lib/python3.5/dist-packages/ pyannotate -w -v "mpf/core/data_manager.py"
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Adding transformation: annotate_json
Refactoring mpf/core/data_manager.py
No changes in mpf/core/data_manager.py
No files need to be modified.
```

However, it definitely found some missing annotations in type_info.json:

```
    {   
        "func_name": "DataManager.__init__",
        "path": "mpf/core/data_manager.py",
        "type_comments": [
            "(mpf.tests.MpfTestCase.TestMachineController, str, int) -> None"
        ],
        "line": 18,
        "samples": 5
    },
```

And the code looks like this:
```
class DataManager(MpfController):

    """Handles key value data loading and saving for the machine."""

    def __init__(self, machine, name, min_wait_secs=1):
        [...]
```

Any idea what is going wrong here?

**Comment by gsalgado** [comment]
I was also bit by this, but got it to work on 3.5 by dumping the type info in the same dir where my source files are located, and invoking pyannotate from there as well. e.g.

> $ pyannotate -w data_manager.py

**Comment by jabdoa2** [comment]
That does not seem to help for me. Same output but no changes to the file.

**Comment by gvanrossum** [comment]
Is there an existing type comment in the `__init__` function?

**Comment by jabdoa2** [comment]
No comments. This was just one example. It did not work on any file in our code base. I verified 10 cases where it should annotate but did not.

**Comment by gvanrossum** [comment]
I'm sorry for your experience. Since it does state that it's refactoring
the file, I recommend adding some print statements to
get_annotation_from_stub() (in pyannotate_tools/fixes/fix_annotate_json.py)
to see where it decides that there is no applicable annotation.

**Comment by jabdoa2** [comment]
https://github.com/missionpinball/mpf/

**Comment by gvanrossum** [comment]
OK, here's the problem. Your project has an `__init__.py` file at the top
level. So essentially you're running pyannotate from inside a package. That
doesn't work. There's code that crawls up the directory tree until it finds
a directory that's not a package, and that code lands at the parent of your
repo. Why do you have it set up like that? Just deleting the toplevel
`__init__.py` makes everything work.

**Comment by jabdoa2** [comment]
Good question. Probably always has been that way. Deleted it and it works fine now. Thanks!
