### ISSUE TITLE
Permission denied for Temp file on Windows

### ISSUE THREAD

**Issue by NeonGraal** [dropbox/pyannotate#25]
When I run "pyannotate --type-info ./annotate.json ." with on Windows (both 2.7.14 and 3.6.3, probably others) , I get the following error:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pyannotate.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pyannotate_tools\annotations\__main__.py", line 45, in main
    generate_annotations_json(infile, tf.name)
  File "c:\python27\lib\site-packages\pyannotate_tools\annotations\main.py", line 58, in generate_annotations_json
    with open(target_path, 'w') as f:
IOError: [Errno 13] Permission denied: 'c:\\temp\\tmp2ui1ku'

A little bit of googling suggests this might be the problem [Permission Denied To Write To My Temporary File](https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file)

**Comment by gvanrossum** [comment]
Ouch. You're right. Fixing this will require changing some API. Do you want to give it a try?

**Comment by NeonGraal** [comment]
Sure. Might take me a couple of days to find the time unfortunately.

**Comment by schlenk** [comment]
Maybe this helps, explains the little magic needed to reopen temp files on windows, might be easier than changing APIs...

https://stackoverflow.com/questions/15169101/how-to-create-a-temporary-file-that-can-be-read-by-a-subprocess/15235559#15235559

**Comment by gvanrossum** [comment]
Reopening because #26 was reverted. I'll redo this without using temporary files.

**Comment by NeonGraal** [comment]
Darn, sorry I missed this.

**Comment by gvanrossum** [comment]
Now fixed by #46 (sorry, I put #26 instead of #25 in the commit msg).
