### ISSUE TITLE
Runtime outputs illegal type comments

### ISSUE THREAD

**Issue by obi1kenobi** [dropbox/pyannotate#34]
During a profiling run, the runtime sometimes outputs type comments that are illegal. The resulting output JSON file cannot be used as the `--type-info` parameter of `pyannotate`, as the type comments cannot be successfully parsed.

This is using Python 3.6 and `pyannotate==1.0.2`; full repro below.

Here are a few examples of the invalid type comments that are generated, and the corresponding parse errors:
```
{
    "path": "venv/lib/python3.6/site-packages/pytz/__init__.py",
    "line": 126,
    "func_name": "timezone",
    "type_comments": [
        "(str) -> pytz.tzfile.Europe/Amsterdam",
        "(str) -> pytz.tzfile.US/Eastern"
    ],
    "samples": 2
}

pyannotate_tools.annotations.parse.ParseError: Invalid type comment: (str) -> pytz.tzfile.Europe/Amsterdam
---------------------
{
    "path": "venv/lib/python3.6/site-packages/pytz/tzfile.py",
    "line": 26,
    "func_name": "build_tzinfo",
    "type_comments": [
        "(str, _io.BufferedReader) -> pytz.tzfile.Europe/Amsterdam",
        "(str, _io.BufferedReader) -> pytz.tzfile.US/Eastern"
    ],
    "samples": 2
}

pyannotate_tools.annotations.parse.ParseError: Invalid type comment: (str, _io.BufferedReader) -> pytz.tzfile.Europe/Amsterdam
---------------------
{
    "path": "venv/lib/python3.6/site-packages/pytz/tzinfo.py",
    "line": 166,
    "func_name": "DstTzInfo.__init__",
    "type_comments": [
        "(Tuple[datetime.timedelta, datetime.timedelta, str], Dict[Tuple[datetime.timedelta, datetime.timedelta, str], pytz.tzfile.US/Eastern]) -> None",
        "(None, None) -> pyannotate_runtime.collect_types.UnknownType"
    ],
    "samples": 5
}

pyannotate_tools.annotations.parse.ParseError: Invalid type comment: (Tuple[datetime.timedelta, datetime.timedelta, str], Dict[Tuple[datetime.timedelta, datetime.timedelta, str], pytz.tzfile.US/Eastern]) -> None
```

Seems like the `/` in the `pytz` type name is causing the problem.

To reproduce:
- clone the GraphQL compiler project: https://github.com/kensho-technologies/graphql-compiler
- check out the master branch, make a Python 3.6 virtualenv, install the project dependencies
- `pip install pytest-annotate`, a plugin for `pytest` that will run PyAnnotate during tests
- `py.test --annotate-output ./annotations.json` which will output PyAnnotate annotations into `annotations.json`
- `pyannotate --type-info ./annotations.json ./graphql_compiler/compiler/compiler_frontend.py`, which will crash with the errors above

**Comment by gvanrossum** [comment]
Wow. It looks like pytz creates a class for each timezone and sets the class `__name__` attribute to the full timezone name. We should either replace class names that don't conform to the "identifier" syntax when collecting, or we should fix these in the parser. I'm inclined to do the latter, so we have some hope of special-casing these.

**Comment by obi1kenobi** [comment]
That sounds good -- I'd also be happy with simply inferring `Any` for classes whose names are unparseable, if that's an easier workaround to add for now.

**Comment by obi1kenobi** [comment]
Thank you for the prompt fix!
