### ISSUE TITLE
mypy 0.620 signals an error on pyannotate

### ISSUE THREAD

**Issue by bluebird75** [dropbox/pyannotate#77]
Using latest mypy 0.620 run on pyannotate triggers the following errors : 

```
pyannotate_runtime/collect_types.py:375: error: The type alias is invalid in runtime context
pyannotate_runtime/collect_types.py:379: error: The type alias is invalid in runtime context
pyannotate_runtime/collect_types.py:380: error: The type alias is invalid in runtime context
```

See : https://travis-ci.org/dropbox/pyannotate/jobs/420859849

This is above my level of understanding of static type usage.

**Comment by gvanrossum** [comment]
Thanks, fixed by aa812e662a0eae3c1922167c6068cb9f39cc735a
